#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as path to the shell.
#
#       For example, if you have ksh installed and /bin/sh is actually bash,
#       you might want to run 'ksh gradlew' or 'bash gradlew' (if you have bash).
#
#   (2) This script points at the properties file at `gradle/wrapper/gradle-wrapper.properties`.
#       If you move or rename that file, make sure to update this script accordingly.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
winnt=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NT* )             winnt=true   ;; #(
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$msys" && ! "$winnt" ; then
    MAX_FD_LIMIT=$( ulimit -H -n )
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" ] || [ "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the classpath 'gradle-launcher-7.4.2.jar' in the wrapper directory
set -- \
        org.gradle.wrapper.GradleWrapperMain \
        "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
        "$@"

# Use "xargs" to parse quoted args.
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
# In Bash we could simply go:
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}"
# Which would all be on one line, but that works only with bash.
# On other shells, we use `set +f` to disable globbing and then `set -- $var`
# to split the variable into args, without splitting on spaces that are quoted.
# (Using `set --` works in POSIX, except for the negative indexing and `set -- $var`
# does not work for bash pre-3.0)
if eval 'set -- $((printf %s "$var" | xargs -n1) 2>/dev/null)' ; then
    set -- $(printf %s "$var" | xargs -n1)
else
    set -- $var
fi

# Split up the JVM_OPTS And GRADLE_OPTS values into an array, following the same quoting rules
# as for the command line, until we have all of them.
jvm_opts_file=""
if [ -f "$APP_HOME/.gradle/jvmopts" ] ; then
    jvm_opts_file="$APP_HOME/.gradle/jvmopts"
    jvm_opts=$(cat "$jvm_opts_file")
fi
if [ -n "$jvm_opts" ] ; then
    set -- $jvm_opts "$@"
fi

# Evaluate the command line arguments for cygwin and similar systems.
if $cygwin ; then
    # Cygwin quoting is quite different, handle separately.
    # Don't use eval to preserve argument quoting.
    set -- $(cygpath --windows -- "$@" | tr '\n' ' ')
elif $msys ; then
    # In MSYS, argument parsing is more complex, some arguments may be in Windows
    # style or MSYS style. We'll just join all arguments with spaces and parse
    # them as a single string to keep things simple.
    set -- $(
        printf '%s ' "$@" | tr ' ' '\n' | sed -e 's/\\\\/\\\\\\\\/g' -e 's/"/\\\\"/g' | xargs printf '"%s" '
    )
fi

# Execute the wrapper.
exec "$JAVACMD" "$@"
